# Generated by Django 5.2.4 on 2025-08-06 15:34

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0002_alter_categoria_nombre_alter_categoria_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, help_text='Se genera automáticamente.', max_length=150, unique=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('lugar', models.CharField(max_length=250)),
                ('entrada', models.CharField(blank=True, max_length=150, null=True)),
                ('google_maps_url', models.URLField(blank=True, max_length=500)),
                ('descripcion', models.CharField(max_length=300)),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField()),
                ('imagen', models.ImageField(default='articulos/default_img_articulo.jpg', upload_to='agenda/')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda', to='categorias.categoria')),
                ('colectividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colectividad_eventos', to='categorias.categoria')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
