# Generated by Django 5.2.4 on 2025-08-07 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='asistencias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evento',
            name='asistentes',
            field=models.ManyToManyField(blank=True, related_name='evento_asist', to=settings.AUTH_USER_MODEL),
        ),
    ]
