# Generated by Django 5.2.4 on 2025-07-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, help_text='Slug para la URL del artículo, se genera automáticamente.', max_length=150, unique=True)),
                ('autor', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos')),
                ('comentarios_habilitados', models.BooleanField(default=True)),
                ('visitas', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
