# Generated by Django 5.2.4 on 2025-07-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_alter_articulo_options_alter_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(default='articulos/default_img_articulo.jpg', upload_to='articulos/'),
        ),
    ]
