# Generated by Django 5.2.4 on 2025-08-04 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_articulo_colectividad_alter_articulo_autor'),
        ('categorias', '0002_alter_categoria_nombre_alter_categoria_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='colectividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colectividad', to='categorias.categoria'),
        ),
    ]
