# Generated by Django 5.2.4 on 2025-08-05 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0007_alter_articulo_colectividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['-creado']},
        ),
    ]
