# Generated by Django 5.2.4 on 2025-08-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0008_alter_articulo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
