# Generated by Django 5.2.4 on 2025-08-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0009_articulo_youtube_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='visitas',
        ),
    ]
