# Generated by Django 5.2.4 on 2025-08-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0010_remove_articulo_likes_remove_articulo_visitas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='youtube_url',
        ),
    ]
