# Generated by Django 5.2.4 on 2025-08-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='titulo',
            field=models.CharField(default='Contacto...', max_length=100),
        ),
    ]
