# Generated by Django 5.2.4 on 2025-08-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_contacto_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='imagen',
            field=models.ImageField(default='articulos/default_img_articulo.jpg', upload_to='nosotros/'),
        ),
    ]
