# Generated by Django 5.2.4 on 2025-08-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_contacto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='direccion',
            field=models.TextField(max_length=200),
        ),
    ]
