# Generated by Django 5.2.4 on 2025-07-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Artículo, Evento, Galeria', max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=25, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=25, unique=True)),
                ('tipos', models.ManyToManyField(blank=True, help_text='Seleccioná los tipos a los que pertenece esta categoría (Ej: Artículo, Evento, Galeria)', related_name='categorias', to='categorias.tipocategoria')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
