# Generated by Django 5.2.4 on 2025-08-05 06:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=40)),
                ('slug', models.SlugField(blank=True, help_text='se genera automáticamente.', unique=True)),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField()),
                ('imagen', models.ImageField(default='articulos/default_img_articulo.jpg', upload_to='nosotros/')),
            ],
            options={
                'ordering': ['creado'],
            },
        ),
    ]
