# Generated by Django 5.2.4 on 2025-08-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosotros',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
